
name: Update wild rift profile

on:
  schedule:
    # Runs "every 2 hours" (see https://crontab.guru)
    - cron: '0 */2 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Feed new profile
        run: curl -X GET https://github-readme-wr-stats-mengxyz.vercel.app/api/profile?profile=uYMx9DHw09rvbi5iFNzH --output ./art/wr_profile.png 
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: art/**/*.png art/**/*.jpg

    
